apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      containers:
      - name: auth-microservice
        image: .../micropay-auth-service-repo:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: SNS_TOPIC_ARN
          value:       
        - name: COGNITO_USER_POOL_ID
          value: 
        - name: COGNITO_CLIENT_ID
          value: 
        - name: COGNITO_CLIENT_SECRET
          value: 
        - name: RDS_HOST
          value: 
        - name: RDS_PORT
          value: "5432"
        - name: RDS_PASS
          value: TestingDB          
        - name: RDS_NAME
          value: postgres          
        - name: RDS_USER
          value: postgres          
---
apiVersion: v1
kind: Service
metadata:
  name: auth-microservice
spec:
  type: ClusterIP # LoadBalancer
  selector:
    app: auth-microservice
  ports:
  - port: 8000
    targetPort: 8000
